baseURL = 'https://eki.moe/'
DefaultContentLanguage = "zh"
languageCode = 'zh-cn'
title = "Eki's Home"
copyright = "2023 Eki"
theme = "diary"

[taxonomies]
   tag = "tags"

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "https://dn42.eki.moe"
name = "DN42"
weight = 3

[[menu.main]]
url = "/friends"
name = "Friends"
weight = 4

[[menu.main]]
url = "/about"
name = "About"
weight = 5

[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 6

[params]
favicon = "/images/favicon.jpg"
cloudflareToken = "bc27981a495345ea8773c82df6c55aaa"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4