baseURL = 'https://eki.moe/'
DefaultContentLanguage = "zh"
languageCode = 'zh-cn'
title = "Eki's Home"
theme = "diary"

[taxonomies]
   tag = "tags"

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/about"
name = "About"
weight = 3

[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 4